#!/bin/bash -

# shblog - static site blog generator
# Author: Oliver Fields, oliver@phnd.net

# Set to known values
IFS=$' \t\n'
PATH=/bin:/usr/bin

# Exit on error
set -e

function error {
  echo "Error: $1" >&2
  exit 1
}

function warning {
  echo "Warning: $1" >&2
}

function usage {
  echo "Usage: $(basename $0) [init [blog dir]|build [blog dir]|]" >&2
  exit 1
}

function build_blog {
  . "$lib_dir/build_posts"
  . "$lib_dir/build-list-pages"
  . "$lib_dir/update-sitemap"
  . "$lib_dir/update-feed"
  cp -R "$blog_dir/includes/"* "$blog_dir/site/."

  if [ "$optimize_site" = "1" ]; then
    . "$lib_dir/optimize_site"
  fi
}

function load_blog_config() {
  if [ -e "$blog_dir/blog.conf" ]; then
    . "$blog_dir/blog.conf"
  else
    error "Unable to load '$blog_dir/blog.conf'"
  fi
}

# Load global config
if [ -e "./shblog.conf" ]; then
  . "./shblog.conf"
elif [ -e "$HOME/.config/shblog.conf" ]; then
  . "$HOME/.config/shblog.conf"
elif [ -e "/etc/shblog.conf" ]; then
  . "/etc/shblog.conf"
else
  error "Unable to load either './shblog.conf', '$HOME/.config/shblog.conf' or '/etc/shblog.conf'"
fi

# Trim any trailing slashes
lib_dir="${lib_dir%/}"
skel_dir="${skel_dir%/}"

if ! [ -e "$lib_dir" ]; then
  error "Unable to load dependencies from '$lib_dir', check 'lib_dir' setting in shblog.conf"
fi

export blog_dir="${2%/}" # Trim any trailing slash                              

if [ "$blog_dir" = "" ]; then
  usage
fi

# Check valid action, then shift arguments to chop off action
cmd="$lib_dir/$1"
case $1 in
  build)
    load_blog_config
    build_blog
  ;;
  init)
    . "$lib_dir/init"
  ;;
  *)
    usage
  ;;
esac
