#!/bin/bash

post_file="$1"

if ! [ -e "$post_file" ]; then
  echo "Unable to find '$post_file'" >&2
  exit 1
fi

# Parse the headers and check correct
while read line; do
  key="${line%%:*}"
  value="${line##*: }"

  # Headers are over when hit first blank line
  if [ "$line" = "" ]; then
    break
  fi

  if [ "$key" = "$value" ]; then
    warning "Header '$key' empty in '$post_file'"
    continue
  fi

  case $key in
    'Title')
      post_title="$value"
      ;;
    'Description')
      post_description="$value"
      ;;
    '')
      break;
      ;;
    *) ;;
  esac 
done < <(cat "$post_file")

post_file_name="${post_file##*/}"

post_date="${post_file_name%%_*}"
post_year="${post_date:0:4}"
post_month="${post_date:4:2}"
post_day="${post_date:6:2}"
post_pretty_date="${post_year}-${post_month}-$post_day"

post_slug="${post_file_name##*_}"
post_url="/$post_year/$post_month/$post_day/$post_slug$html_extension"

echo "<div class=\"post_list_view\">
<h2 class=\"post_title\"><a href=\"$post_url\">$post_title</a></h2>
<div class=\"post_date\">$post_pretty_date</div>
<p class=\"post_description\">$post_description</p>
</div><!-- /post_list_view -->"
