#!/bin/bash

# Generate static pages listing blogposts

if ! [ -e "$blog_dir/post_source" ]; then
  error "Directory '$blog_dir/post_source' not found"
fi

if [ "$max_frontpage_posts" = "" ]; then
  max_frontpage_posts=7
fi

{
  while read line; do
    case $line in
      '##title##')
        echo "<title>$blog_title_prefix$frontpage_title$blog_title_suffix</title>"
        ;;
      '##description##')
        echo "<meta name=\"description\" content=\"$blog_description\" />"
        ;;
      '##base_url##')
         echo "<base href=\"$blog_base_url\" />"
         ;;
      '##canonical##')
        echo "<link rel=\"canonical\" href=\"$blog_base_url/\" />"
        ;;
      *)
        echo "$line"
        ;;
    esac
  done < "$blog_dir/html_parts/header.html"
  echo '<div id="wrapper">
<div id="post_list">'
  if [ "$thumbnail_width" != "" ]; then                                       
    img_width=" width=\"$thumbnail_width\""
  fi
  if [ "$thumbnail_height" != "" ]; then
    img_height=" height=\"$thumbnail_height\""
  fi
  for post_file in $(ls -r "$blog_dir/post_source/"* | head -$max_frontpage_posts); do
    . "$lib_dir/post_list_view" "$post_file"
  done
  echo '</div><!-- /post_list -->'
  echo "<div><a href=\"/archive$html_extension\">Older posts</a></div>"
  echo '</div><!-- /wrapper -->'
  cat "$blog_dir/html_parts/footer.html"
} > "$blog_dir/site/index$html_extension"
